services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    command: bun run --hot ./src/server.ts
    develop:
      watch:
        - action: sync
          path: ./src
          target: /src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
